### ISSUE TITLE
Tools Diagnostics Test Fails

### ISSUE THREAD

**Issue by spficklin** [tripal/GalaxyLib-PHP#17]
When testing the GalaxyTools::diagnostic function this error is returned:

Uncaught exception in exposed API method

The URL is identical to that used in the GalaxyTools::show function but with the word diagnostic at the end.

**Comment by cwytko** [comment]
Default tools will have the diagnostics, but some tools do not have it. 
I'm resorting to hardcoding the 'upload1' tool because some of the tools will be without the diagnostics (especially the ones that are custom tools (that are not required to have a diagnostics), rendering this test to throw an error
